spring.application.name= InternshipMileStone
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/InternshipMileStoneProject
spring.datasource.username= postgres
spring.datasource.password= ${CONNECTIONPASSWORD}
spring.jpa.hibernate.ddl-auto= update
spring.jpa.properties.hibernate.auto_quote_keyword= true

server.reactive.session.cookie.same-site= strict
server.servlet.context-path= /api
jwt.secret = ${InternshipMilestone jwt-secret}

jwt.expiration=86400000
attendance.required-hours = 8.0


